<?php
header("Access-Control-Allow-Origin: *");
include_once('db.php');

error_reporting(0);
$Newval =$_POST['Newval'];

$sQueryString="SELECT LA.KHASRA_NO, LA.KHATA_NUMBER, LA.WET_LAND_AREA, LA.DRY_LAND_AREA, LA.AREA_OF_LAND, 
LA.AREA_OF_SETTLEMENT, LA.SURVEY_NO_OF_LAND, LA.STATUS_OF_LAND, LHT.ENUM_ID, LHT.DESCRIPTION, 
LHT.DESCRIPTION_HINDI, GP.LATITUDE, GP.LONGITUDE, FA.FIXED_ASSET_ID, FA.FIXED_ASSET_TYPE_ID, 
FA.PARENT_FIXED_ASSET_ID, FA.INSTANCE_OF_PRODUCT_ID, FA.CLASS_ENUM_ID, FA.PARTY_ID, FA.ROLE_TYPE_ID, 
FA.FIXED_ASSET_NAME, FA.ACQUIRE_ORDER_ID, FA.ACQUIRE_ORDER_ITEM_SEQ_ID, FA.DATE_ACQUIRED, 
FA.DATE_LAST_SERVICED, FA.DATE_NEXT_SERVICE, FA.EXPECTED_END_OF_LIFE, FA.ACTUAL_END_OF_LIFE,
 FA.PRODUCTION_CAPACITY, FA.UOM_ID, FA.CALENDAR_ID, FA.SERIAL_NUMBER, FA.LOCATED_AT_FACILITY_ID, 
 FA.LOCATED_AT_LOCATION_SEQ_ID, FA.SALVAGE_VALUE, FA.DEPRECIATION, FA.PURCHASE_COST, 
 FA.PURCHASE_COST_UOM_ID, FA.RD_DISTANCE, FA.CURRENT_LOCATION, FA.STATUS, FA.FULL_RESERVOIR_LEVEL, 
 FA.GROSS_CAPACITY, FA.ASSET_LEVEL_MAX_VALUE, FA.ASSET_LEVEL_MIN_VALUE, FA.DESIGNED_POTENTIAL_RABI, 
 FA.DESIGNED_POTENTIAL_KHARIF, FA.AVERAGE_LIVE_CAPACITY, FA.DESIGNED_POTENTIAL_OTHER_AREA, 
 FA.ANNUAL_IRRIGATION_AREA, FA.BASIN_ID, FA.CIRCLE_ID, FA.DIVISION_ID, FA.SUB_DIVISION_ID, 
 FA.ASSET_TRANSFER_ID, FA.FIXED_ASSET_NAME_HINDI, FA.OTHER_OFFICE_FLAG, FA.DHI_STATUS, FA.STATUS_ID, 
 FA.FSM_SCHEME_ID FROM (((public.FIXED_ASSET FA LEFT OUTER JOIN public.FIXED_ASSET_GEO_POINT FAGP ON 
 FA.FIXED_ASSET_ID = FAGP.FIXED_ASSET_ID) LEFT OUTER JOIN public.GEO_POINT GP ON FAGP.GEO_POINT_ID = GP.GEO_POINT_ID) 
 LEFT OUTER JOIN public.LAND_ASSET_DETAILS LA ON FA.FIXED_ASSET_ID = LA.FIXED_ASSET_ID) LEFT OUTER JOIN 
 public.ENUMERATION LHT ON LA.LAND_HOLDING_TYPE = LHT.ENUM_ID WHERE FA.PARTY_ID ='$Newval'
";

$result = pg_query($sQueryString );
$aRows=array();
$ii=1;
while($row = pg_fetch_object($result)) {
  $aRows[]=$row;
  $ii++;
}

//print_r(json_encode($aRows)); 

print(json_encode($aRows, JSON_UNESCAPED_UNICODE));
//mysqli_close($conection);


?>
